### PR TITLE
feat: output version info to stdout

### PR DESCRIPTION
**Pull request by jbrockopp**
This updates the `github.com/go-vela/server` app to output the version information to stdout on startup:

```sh
$ docker logs server
{
  "canonical": "v0.8.2",
  "major": 0,
  "minor": 8,
  "patch": 2,
  "metadata": {
    "architecture": "amd64",
    "build_date": "2021-06-15T08:57:00Z",
    "compiler": "gc",
    "git_commit": "7ed708324825cc05e596306093a2855da47330c7",
    "go_version": "go1.16.5",
    "operating_system": "linux"
  }
}
<more logs>
```

### CODE REVIEW

**Review by matt-fevold — APPROVED** [review]
great idea - LGTM

**Review by matt-fevold — CHANGES_REQUESTED** [review]
When reviewing the worker PR i see you updated one `err :=` ref later on to `err =` 

Is that not needed here too?

https://github.com/go-vela/server/pull/429/files#diff-dc189c3a5470d24230c46570e8bbb88c1faae799eac6e75f45c01ad204bdcab4L172

**Comment by jbrockopp** [comment]
@matt-fevold the reason that change isn't applied here is because the assignment to `err` happens inside of the `if`.

However, I'll update the code here to look more like the worker that way we are consistent! 👍

**Comment by jbrockopp** [comment]
@matt-fevold this should be complete 😃

**Review by matt-fevold — APPROVED** [review]
Ahhh makes sense :) Noice!

**Review by wass3r — APPROVED** [review]

**Pull request merged**
