### PR TITLE
chore(yaml): add go-yaml types package

### PR DESCRIPTION
**Pull request by ecrupper**
I am breaking up https://github.com/go-vela/server/pull/1220 into more digestible PRs.

This PR simply adds the new `go-yaml` v3 library types package: `compiler/types/yaml/yaml`. All unmarshaled buildkite YAML gets converted to that type since they are identical post-parsing.

In other words, there is no functional change in this PR. But it sets the stage much better for future changes to make those PRs easier to understand.

### CODE REVIEW

**Review by wass3r — APPROVED** [review]
i'll reapprove when conflicts are solved

**Review by wass3r — DISMISSED** [review]

**Comment by wass3r** [comment]
test failed on schema validator 🤔 i confirmed it works fine on main branch. but if you run command manually, you can see the actual error (probably something to improve in the actions workflow).

```❯ jv schema.json schema/testdata/pipeline/pass/complex.yml
schema schema.json: ok

instance schema/testdata/pipeline/pass/complex.yml: failed
jsonschema validation failed with 'file:///home/name/ghq/github.com/go-vela/server/schema.json#'
- at '/stages': got object, want array
```

so, the generated schema differs. i confirmed locally:
```diff
❯ diff schema.json schema_old.json
3c3
<   "$id": "https://github.com/go-vela/server/compiler/types/yaml/yaml/build",
---
>   "$id": "https://github.com/go-vela/server/compiler/types/yaml/build",
798,799c798,801
<       "items": {
<         "$ref": "#/$defs/Stage"
---
>       "patternProperties": {
>         ".*": {
>           "$ref": "#/$defs/Stage"
>         }
801c803,804
<       "type": "array"
---
>       "additionalProperties": false,
>       "type": "object"```

**Review by wass3r — APPROVED** [review]
looks good!

just wanted to point out that none of the json schema methods moved with yaml/buildkite except for https://github.com/go-vela/server/blob/0f945922fa92bd93bd12ac77eef41e76ed511679/compiler/types/yaml/buildkite/stage.go#L135 - not an issue per se, just odd. we're moving away from buildkite, so no big deal.

**Review by KellyMerrick — APPROVED** [review]
lgtm

**Pull request merged**
