### PR TITLE
chore(release): upgrade types to v0.20.0 and upgrade other deps

### PR DESCRIPTION
**Pull request by ecrupper**
Closes https://github.com/go-vela/server/pull/905
Closes https://github.com/go-vela/server/pull/904
Closes https://github.com/go-vela/server/pull/903

### CODE REVIEW

**Review by KellyMerrick — DISMISSED** [review]
lgtm

**Review by plyr4 — DISMISSED** [review]

**Review by wass3rw3rk — APPROVED** [review]

**Review by wass3rw3rk — CHANGES_REQUESTED** [review]
wrong docker reference

**Review by KellyMerrick — DISMISSED** [review]
lgtm

**Review by wass3rw3rk — APPROVED** [review]

**Review by KellyMerrick — APPROVED** [review]
lgtm

**Pull request merged**
