### PR TITLE
fix(open-api): Reorganize the login/authenticate swagger definitions

### PR DESCRIPTION
**Pull request by slushpupie**
This reorganizes the swagger spec for /login and /authenticate endpoints. No code changes.

### CODE REVIEW

**Review by jbrockopp — CHANGES_REQUESTED** [review]
LGTM 👍 

However, do we need to regenerate the swagger spec as well?

I believe the comments being changed here would impact the output of that document.

Thoughts?

**Comment by slushpupie** [comment]
Yes, With #205 merged, I'll rebase this one and generate the spec.

**Comment by slushpupie** [comment]
@jbrockopp Updated and regenerated.  Should be good to go now.

**Review by jbrockopp — APPROVED** [review]
LGTM

**Review by wass3r — APPROVED** [review]

**Pull request merged**
