### PR TITLE
feat: adding raw pipeline validation endpoint

### PR DESCRIPTION
**Pull request by GregoryDosh**
To support the request in https://github.com/go-vela/community/issues/292 this aims to give tools (and users) an ability to send in raw .vela.yml files for the server to validate. The goal is to be able to use the server's capability to expand templates in conjunction with a local .vela.yml file in order to rapidly prototype a new CI or iteratively change a CI without having to push changes to Git constantly.

Looking for input on all the different design and code choices as this was done through a Hackathon between a few folks. We know it isn't perfect, but want to get the ball rolling on comments and updates/etc.

Things for sure missing include:
- [ ] Swagger Spec

To use this from the CLI there are 2 other PRs submitted that I'll link to this server PR.
- https://github.com/go-vela/cli/pull/241
- https://github.com/go-vela/sdk-go/pull/108

### CODE REVIEW

**Comment by GregoryDosh** [comment]
Right now the pipeline is being passed in as a data structure that looks like
```json
"dmVyc2lvbjogIjEiCgp0ZW1wbGF0ZXM6CiAgLSBuYW1lOiBzc2gtdGVtcGxhdGUKICAgIHNvdXJjZTogZmlsZTovL3NvbWUtcGF0aC1oZXJlCiAgICBmb3JtYXQ6IHN0YXJsYXJrCiAgICB0eXBlOiBsb2NhbAoKc3RlcHM6CiAgLSBuYW1lOiAic29tZSB0ZW1wbGF0ZSB0eXBlIHN0ZXAiCiAgICB0ZW1wbGF0ZToKICAgICAgbmFtZTogc3NoLXRlbXBsYXRlCg=="
```

But thinking towards the future and some of the other features, it might make sense to talk about a better format...perhaps something like
```json
{
  "pipeline_format": "yaml",
  "encoded_pipeline": "dmVyc2lvbjogIjEiCgp0ZW1wbGF0ZXM6CiAgLSBuYW1lOiBzc2gtdGVtcGxhdGUKICAgIHNvdXJjZTogZmlsZTovL3NvbWUtcGF0aC1oZXJlCiAgICBmb3JtYXQ6IHN0YXJsYXJrCiAgICB0eXBlOiBsb2NhbAoKc3RlcHM6CiAgLSBuYW1lOiAic29tZSB0ZW1wbGF0ZSB0eXBlIHN0ZXAiCiAgICB0ZW1wbGF0ZToKICAgICAgbmFtZTogc3NoLXRlbXBsYXRlCg==",
  "local_templates": [
    {
      "name": "ssh-template",
      "format": "starlark",
      "encoded_template": "ZGVmIG1haW4oY3R4KToKICByZXR1cm4gewogICAgJ3ZlcnNpb24nOiAnMScsCiAgICAnc3RlcHMnOiBbCiAgICAgIHsKICAgICAgICAnbmFtZSc6ICdidWlsZCcsCiAgICAgICAgJ2ltYWdlJzogY3R4WyJ2YXJzIl1bImltYWdlIl0sCiAgICAgICAgJ2NvbW1hbmRzJzogWwogICAgICAgICAgJ2dvIGJ1aWxkJywKICAgICAgICAgICdnbyB0ZXN0JywKICAgICAgICBdCiAgICAgIH0sCiAgICBdLAp9Cg=="
    }
  ]
}
```

**Review by jbrockopp — CHANGES_REQUESTED** [review]
Thanks for the contribution! 🎉 

We looked over this today with various members of the team! 👍 

One concern brought up was we would like to see the swagger spec information added 😄 

We saw in your original PR body you made mention that was still to be completed.

Perhaps that's a good place to start?

**Comment by GregoryDosh** [comment]
Sorry for the delay on this PR. Going to tackle more of this this weekend or later this week I hope. Been dealing with moving and internet stuffs so been off the grid for a little while.

**Comment by GregoryDosh** [comment]
Before merging something like this new feature, I'm going to spend some time working on #478 to clean up this file so there is less duplicative code blocks.

**Comment by KellyMerrick** [comment]
Has this effort been covered with https://github.com/go-vela/cli/pull/248 being merged in?

**Comment by GregoryDosh** [comment]
@KellyMerrick I think some aspect of the functionality is covered in that PR, and really the only additional functionality this whole rewrite might expose would be an ability to expand/interpolate templates from an API call instead (think a new page in the UI to develop or test/validate templates).  For now though it probably makes sense to close this and re-open if a new need arises.

**Pull request closed without merging**
