### PR TITLE
fix(ci): add patch to PR title validator

### PR DESCRIPTION
**Pull request by ecrupper**

### CODE REVIEW

**Review by jbrockopp — APPROVED** [review]
LGTM

**Review by wass3r — COMMENTED** [review]
What's the difference between patch and fix?

**Comment by ecrupper** [comment]
> What's the difference between patch and fix?

whenever cutting a patch release, I like to use `patch(...)` so I can distinguish between PRs to `main` and PRs to a patch release branch. Personal preference tbh

**Comment by plyr4** [comment]
looks good to me
though we should add `patch` (and anything else in this validator) to the development workflow style guide as one of the preferred titles:
https://go-vela.github.io/docs/community/contributing_guidelines/#development-workflow

**Comment by wass3rw3rk** [comment]
@ecrupper @plyr4 agree. if this is a new pattern for the team, we should add some notes somewhere.

**Pull request closed without merging**
