### PR TITLE
enhance(starlark): make execution step limit configurable

### PR DESCRIPTION
**Pull request by ecrupper**
Ref: https://github.com/go-vela/server/pull/943

Since we don't have a good idea on how to potentially calculate a limit, it's a good idea to make this value configurable on start up, rather than incrementing it whenever we run into problems.

Default is set to 7500, though I'm open to other ideas on that 👍 .

### CODE REVIEW

**Review by colindean — COMMENTED** [review]
You might want to have a "Starlark execution environment" config struct where this limit and inevitably other stuff gets shoved. It would perhaps include the environment name, e.g.

```go
thread := &starlark.Thread{Name: "templated-base"}
```

Also, there's still a hardcoded step limit in the `Render` method on around line 41-42.

**Review by plyr4 — DISMISSED** [review]

**Review by wass3r — DISMISSED** [review]

**Review by wass3rw3rk — APPROVED** [review]

**Comment by wass3r** [comment]
@colindean what is the use case for controlling the thread name? or was that just arbitrarily chosen as an example for making it more extensible?

**Comment by colindean** [comment]
Arbitrarily chosen. Wouldn't be surprised if there's other things in there that end up needing to be tuned

**Comment by colindean** [comment]
For that config could also include things for controlling the inevitable subprocess, like a timeout, memory limits, etc

**Review by KellyMerrick — APPROVED** [review]
lgtm

**Pull request merged**
