### PR TITLE
fix(hook/webhook)!: clean up rename repo code with EventAction and shift defer func

### PR DESCRIPTION
**Pull request by ecrupper**
Closes https://github.com/go-vela/community/issues/586

With the defer function being declared before the `nil` build check, any repository event was resulting in an error since there was no `repo_id` in the hook object. Also, cleaning up the repository renaming code by adding the `event_action` field to hook.

### CODE REVIEW

**Review by cognifloyd — DISMISSED** [review]
LGTM

**Review by jbrockopp — APPROVED** [review]
LGTM

**Review by wass3r — APPROVED** [review]
should be in v0.14 - we'll have to update the migrations utility

**Comment by wass3r** [comment]
added to migration utility PR: https://github.com/go-vela/community/pull/592/commits/04d422a0daeddd990c74fed9862e475153a29ce0

**Pull request merged**
